# Generated by Django 3.0.6 on 2020-05-30 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MgtApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date_of_consultation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 18, 31, 31, 482422, tzinfo=utc)),
        ),
    ]
