# Generated by Django 3.0.6 on 2020-05-30 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MgtApp', '0002_auto_20200530_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.EmailField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='date_of_consultation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 18, 43, 24, 923373, tzinfo=utc)),
        ),
    ]
