# Generated by Django 3.0.6 on 2020-05-30 18:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MgtApp', '0003_auto_20200530_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='user',
        ),
        migrations.AlterField(
            model_name='patients',
            name='date_of_consultation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 18, 45, 57, 489939, tzinfo=utc)),
        ),
    ]
