# Generated by Django 3.0.6 on 2020-05-30 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MgtApp', '0004_auto_20200530_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date_of_consultation',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 18, 46, 17, 805312, tzinfo=utc)),
        ),
    ]
